In [3]:
import cv2
import numpy as np
import os
import glob
 
# Defining the dimensions of checkerboard
CHECKERBOARD = (6,5)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 
 
 
# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None
 
# Extracting path of individual image stored in a given directory
images = glob.glob('/Users/kanjisugimori/Documents/VS_Code/*.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
    print(ret)
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    cv2.imshow('img',img)
    cv2.waitKey(0)
 
cv2.destroyAllWindows()

ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)
 

True
False
False
False
False
False
True
True
False
False
False
False
Camera matrix : 

[[1.49082247e+03 0.00000000e+00 9.89406025e+02]
 [0.00000000e+00 1.49799612e+03 5.71826510e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dist : 

[[-1.96472816e+00  9.61621868e+01 -1.80150196e-02  1.36373363e-02
  -1.34299646e+03]]
rvecs : 

(array([[1.1075548 ],
       [0.34633783],
       [2.81072647]]), array([[-0.57195179],
       [-0.45003304],
       [-2.52892066]]), array([[-0.25261833],
       [-0.14645182],
       [-1.58574917]]))
tvecs : 

(array([[-0.67784738],
       [ 2.8113376 ],
       [25.89902439]]), array([[-0.96253659],
       [ 0.61741248],
       [22.98547152]]), array([[-3.89779009],
       [ 4.10597939],
       [23.09334127]]))
